Algoritmo "fatorial"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : denicoli
// Data atual  : 30/11/2022
Var
num: inteiro
fatorial: inteiro
soma :inteiro
Inicio
soma<- 1
escreva ("digite o numero que quer fazer o fatorial: ")
leia (num)
para fatorial de 1 ate num faca
soma <- soma*fatorial
escreval (soma)
fimpara

Fimalgoritmo