Algoritmo "metade"
// 
//  
// Descrição   :Escreva um algoritmo em PORTUGOL que receba dez números do usuário e imprima a metade de cada número.
// Autor(a)    : denicoli
// Data atual  : 30/11/2022
Var
num : inteiro
metade: real
quantidade : inteiro

Inicio
para num de 1 ate 10 faca
escreval ("Digite um numero: ")
leia (num)
metade <- num/2
escreval ("A metade desse numero é: ",metade)

fimpara
Fimalgoritmo