Algoritmo "raizquadrada"
// 
//  
// Descrição   : Escreva um algoritmo em PORTUGOL que receba quinze números do usuário e imprima a raiz quadrada de cada número.
// Autor(a)    : denicoli
// Data atual  : 30/11/2022
Var
num: inteiro
raiz: real

Inicio
para num de 1 ate 15 faca
escreva ("Digite um numero: ")
leia (num)
raiz <- raizq(num)
escreval ("A raiz quadrada desse numero é: ", raiz:10:2)

fimpara
Fimalgoritmo