Algoritmo "soma_para"
// 
//  
// Descrição   :Criar um algoritmo em PORTUGOL que imprima todos os números de 1 até 100,inclusive, e a soma de todos eles.

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/11/2022
Var
num  : inteiro
soma: inteiro


Inicio
soma <- 0
para num de 1 ate 100 faca
soma <- soma + num
escreval (num)
fimpara
escreval ("A soma desses numeros é: ",soma)
Fimalgoritmo