Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/11/2022
Var
num: inteiro
valor: real

Inicio
escreva ("Digite o numero que quer fazer a tabuada: ")
leia (valor)
para num de 1 ate 10 faca
escreval(valor*num)
fimpara

Fimalgoritmo