Algoritmo "válido_ou_inválido"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleberson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : denicoli
// Data atual  : 16/11/2022
Var

sexo : caracter


Inicio
escreva ("Digite seu a inicial de seu sexo: ")
leia (sexo)
         se (sexo = "f") ou (sexo = "m") entao
escreva ("sexo válido")
         senao
         escreva ("sexo inválido")
        fimse


Fimalgoritmo